alias: Mobil fundet Victoria
trigger:
- platform: state
  entity_id: sensor.smoke_alarm
  to: smoke
action:
- service: notify.mobile_app_kontor_oneplus
  data:
    title: Din mobil er fundet
    message: Hold nu styr på hvor du smider den!
    data:
      ttl: 0
      priority: high
      channel: alarm_stream
id: 50766b1cb6b34d6f89d4a50bdb8341c2