alias: Mobil fundet Frederik
trigger:
- platform: state
  entity_id: sensor.smoke_alarm
  to: smoke
action:
- service: notify.mobile_app_frederik_sm_g988b
  data:
    title: Din mobil er fundet
    message: Hold nu styr på hvor du smider den!
    data:
      ttl: 0
      priority: high
      channel: alarm_stream
id: d2ba46bc32f24b53a4e546b5860a21bb