alias: 'Bryggers Toggle'
id: bryggerslys
initial_state: 'on'
trigger:
  platform: event
  event_type: deconz_event
  event_data:
    id: tradfri_remote_kommode
    event: 1002
action:
  service: light.toggle
  entity_id: light.61850762840d8e7b2143