alias: Mobil fundet Trine
trigger:
- platform: state
  entity_id: sensor.smoke_alarm
  to: smoke
action:
- service: notify.mobile_app_trinesm_g986b
  data:
    title: Din mobil er fundet
    message: Hold nu styr på hvor du smider den!
    data:
      ttl: 0
      priority: high
      channel: alarm_stream
id: 96ad8355f6ed42fc8e8c75ff21deaa79