alias: 'SamsungLaderToggleTestRemote'
id: SamsungLaderToggleTestRemote
initial_state: 'on'
trigger:
  platform: event
  event_type: deconz_event
  event_data:
    id: tradfri_remote_test
    event: 2002
action:
  service: switch.toggle
  entity_id: switch.ladersamsungs20ultra